services:
  web:
    build: .
    container_name: myproject_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=.onrender.com,127.0.0.1,13.55.221.108
      - DATABASE_URL=postgres://local_user:local_password@127.0.0.1:5432/eazyweddings

  db:
    image: postgres:14
    container_name: myproject_db
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: myproject
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
